onlineLibraryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.onlineLibraryTable.name}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S      
    KeySchema:
      - AttributeName: PK
        KeyType: "HASH"
      - AttributeName: SK
        KeyType: "RANGE"
    